name: continuous-deployment
on:
  push:
    branches:
      - develop
      - master
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker registry
        run: docker login 'ghcr.io' --username='damlys' --password='${{ secrets.GITHUB_TOKEN }}'
      - name: Set Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Clone Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: ./.semver
      - if: github.event_name == 'push'
        name: Install NPM modules
        working-directory: ./.semver
        run: npm ci
      - if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        name: Bump version (prerelease)
        working-directory: ./.semver
        run: npm run release -- --release-as='patch' --prerelease='rc'
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump version (release)
        working-directory: ./.semver
        run: npm run release -- --release-as='patch'

      - name: Link docker-compose.override.yml
        run: ln -s ./.github/docker-compose.override.yml .
      - name: Build Docker images
        run: docker-compose build
      - name: Run Docker vulnerability scanning
        run: docker scan --severity=high "$(docker-compose config --format=json | jq --join-output .services.app.image)"
        continue-on-error: true

      - name: Run Composer vulnerability scanning
        run: docker-compose run --no-TTY --no-deps --rm app composer run-script vulnerability-scan
        continue-on-error: true
      - name: Run code format check
        run: docker-compose run --no-TTY --no-deps --rm app composer run-script format-check
      - name: Run code lint check
        run: docker-compose run --no-TTY --no-deps --rm app composer run-script lint-check
      - name: Run unit tests
        run: docker-compose run --no-TTY --no-deps --rm app composer run-script unit-tests

      - name: Run Docker containers
        run: docker-compose up --detach
      - name: Wait 10s
        run: sleep 10
      - name: Run HTTP API tests
        run: docker-compose exec --no-TTY app composer run-script http-api-tests
      - name: Destroy Docker containers
        run: docker-compose down --volumes --remove-orphans

      - if: github.event_name == 'push'
        name: Publish Docker images
        run: docker-compose push
      - if: github.event_name == 'push'
        name: Publish version
        run: git push && git push --tags

      - if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        name: Deploy to staging
        run: echo 'Deploying to staging...'
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Deploy to production
        run: echo 'Deploying to production...'
